version: '3'
services:
  app:
    build:
      dockerfile: Dockerfile
      context: .
    image: iuppsample
    container_name: iuppsample
    environment:
      - "localhost:4222=nats://nats:4222"
    ports:
      - "8082:8082"
    depends_on:
      - nats
  nats:
    image: 'nats:0.8.0'
    entrypoint: "/gnatsd -DV"
    expose:
      - "4222"
    ports:
      - "8222:8222"
    hostname: nats-server
