micronaut:
  env:
    deduction: false
  environments: dev
  server:
    port: 8082
    netty:
      log-level: DEBUG
  application:
    name: demo
endpoints:
  health:
    enabled: true
nats:
  addresses:
    - "nats://nats-cluster.nats-io:4222"
  username: "nats-user"
  password: "RYe6uCUFxC8q"
