micronaut:
  server:
    port: 8082
    netty:
      log-level: DEBUG
  application:
    name: demo
endpoints:
  health:
    enabled: true
nats:
  addresses:
    - "localhost:4222"
  username: guest
  password: guest