micronaut:
  server:
    port: 8082
    netty:
      log-level: DEBUG
  application:
    name: demo
endpoints:
  health:
    enabled: true
nats:
  enabled: false
  addresses:
    - "nats://nats-user:RYe6uCUFxC8q@nats-cluster.nats-io:4222"
  max-reconnect: 2
  utf8support: true
  ping-interval: 5