micronaut:
  environments: dev
  server:
    port: 8082
    netty:
      log-level: DEBUG
  application:
    name: demo
endpoints:
  health:
    enabled: true
nats:
  addresses:
    - "nats://localhost:4223"
  username: guest
  password: guest
