micronaut:
  server:
    port: 8082
    netty:
      log-level: DEBUG
  application:
    name: demo
endpoints:
  health:
    enabled: true
nats:
  addresses:
    - "nats://localhost:4222"
  username: "dark-lord"
  password: "qUzfnpj2JudVcuqYpuTihRJE"